investment/home/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views
urlpatterns = [
    path('login/', auth_views.LoginView.as_view(template_name='home/login.html'),name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='home/login.html'),name='logout'),
    path('home', views.home,name='home'),
]

investment/investment/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include
from django.contrib.auth import views as auth_views
from registrations import views
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('cal_returns.urls')),
    path('', include('chartapp.urls')),
    path('', include('home.urls')),
    path('', include('shares.urls')),
    path('', include('savings.urls')),
    path('accounts/',include("registrations.urls")),
    path("", views.login_user, name="login"),
]

investment/savings/urls.py
from django.urls import path
from . import views
urlpatterns = [
    path('savings', views.get_saving_accounts, name='bank-acct-details'),
    path('savings/add', views.create_account_view, name='add_savings_acct'),
    path('savings/update/<int:pk>', views.update_bank_account, name='update_savings_acct'),

    path('transaction', views.get_bank_transaction, name='get_acct_transaction'),
    path('transaction/<int:pk>', views.get_bank_transaction_for_account, name='get_acct_transaction_for_account'),
    path('transaction/add', views.create_bank_transaction, name='add_acct_transaction'),
    path('transaction/update/<int:pk>', views.update_bank_transaction, name='update_acct_transaction'),

    path('categories', views.get_accounts_categories, name='bank-acct-categories'),
    path('categories/add', views.create_account_category, name='add_savings_acct_category'),
    path('categories/update/<int:pk>', views.update_account_category, name='update_savings_acct_category'),
]

investment/savings/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse
from datetime import date


class BankAccount(models.Model):
    acct_types = [
        ('SAVING', 'SAVING'),
        ('FD', 'FD'),
        ('PPF', 'PPF')
    ]

    acct_number = models.CharField(max_length=30)
    acct_type = models.CharField(max_length=10, choices=acct_types)
    acct_name = models.CharField(max_length=30)
    owner = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, blank=True)
    initial_balance = models.FloatField()
    balance = models.FloatField(default=0)

    def get_absolute_url(self):
        return reverse('bank-acct-details')


class TransactionCategory(models.Model):
    category = models.CharField(max_length=50)


class BankTransactions(models.Model):
    txn_type_choices = [
        ('CREDIT', 'CREDIT'),
        ('DEBIT', 'DEBIT')
        ]

    txn_date = models.DateField()
    txn_type = models.CharField(max_length=10, choices=txn_type_choices)
    txn_amount = models.FloatField()
    bank_account = models.ForeignKey(BankAccount, on_delete=models.SET_NULL, null=True, blank=True)
    owner = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, blank=True)
    txn_category = models.ForeignKey(TransactionCategory, on_delete=models.SET_NULL, null=True, blank=True)

investment/savings/forms.py
from django.forms import ModelForm
from .models import BankAccount, BankTransactions, TransactionCategory


class BankAccountForm(ModelForm):
    class Meta:
        model = BankAccount
        exclude = ['owner', 'balance']


class BankAccountTransactionForm(ModelForm):
    class Meta:
        model = BankTransactions
        exclude = ['owner', 'balance']


class TransactionCategoryForm(ModelForm):
    class Meta:
        model = TransactionCategory
        fields = ['category']

investment/savings/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .models import BankAccount, BankTransactions, TransactionCategory
from .forms import BankAccountForm, BankAccountTransactionForm, TransactionCategoryForm
from django.contrib.auth.decorators import login_required


@login_required
def get_saving_accounts(request):
    accounts = BankAccount.objects.filter(owner=request.user)
    print(request.user)
    context = {"accounts": BankAccount.objects.filter(owner=request.user)}
    for acct in accounts:
        print(acct.acct_number, acct.owner)
    return render(request, 'savings/account_list.html', context=context)


@login_required()
def create_account_view(request):
    form = BankAccountForm()
    if request.method == 'GET':
        return render(request, "savings/bankaccount_form.html", {'form': form})
    elif request.method == 'POST':
        form = BankAccountForm(request.POST)
        if form.is_valid():
            obj = form.save(commit=False)
            obj.owner = request.user
            obj.save()
        else:
            print(form)
        return redirect('bank-acct-details')


@login_required()
def update_bank_account(request, pk):
    obj = get_object_or_404(BankAccount, id=pk)
    form = BankAccountForm(request.POST or None, instance=obj)
    error = ""
    if request.user != obj.owner:
        error = "You are not allowed to update this account"
    if form.is_valid() and request.user == obj.owner:
        form_obj = form.save(commit=False)
        form_obj.save()
        return redirect('bank-acct-details')
    if request.user != obj.owner:
        form = BankAccountForm()
    # add form dictionary to context
    context = {"form": form, "error": error}
    return render(request, "savings/bankaccount_form.html", context)


@login_required()
def get_bank_transaction(request):
    transactions = BankTransactions.objects.filter(owner=request.user)
    print(transactions)
    context = {"transactions": transactions}
    return render(request, "savings/transaction_list.html", context=context)

@login_required()
def get_bank_transaction_for_account(request,pk):
    transactions = BankTransactions.objects.filter(owner=request.user).filter(bank_account=pk)
    print(transactions)
    context = {"transactions": transactions}
    return render(request, "savings/transaction_list.html", context=context)

@login_required()
def create_bank_transaction(request):
    form = BankAccountTransactionForm()

    if request.method == 'GET':
        accounts = BankAccount.objects.filter(owner=request.user)
        txn_categories = TransactionCategory.objects.all()
        return render(request, "savings/banktransactions_form.html",
                      {'form': form, 'accounts': accounts, 'categories': txn_categories})
    elif request.method == 'POST':
        form = BankAccountTransactionForm(request.POST)
        if form.is_valid():
            obj = form.save(commit=False)
            obj.owner = request.user
            print(obj.bank_account)
            obj.save()
        else:
            print(form)
        print("I am in new method")
        return redirect('get_acct_transaction')


@login_required()
def update_bank_transaction(request, pk):
    obj = get_object_or_404(BankTransactions, id=pk)
    form = BankAccountTransactionForm(request.POST or None, instance=obj)
    if form.is_valid():
        form.save()
        return redirect('get_acct_transaction')
    accounts = BankAccount.objects.filter(owner=request.user)
    txn_categories = TransactionCategory.objects.all()
    context = {"form": form, 'accounts': accounts, 'categories': txn_categories}
    return render(request, "savings/banktransactions_form.html", context)


@login_required
def get_accounts_categories(request):
    categories = TransactionCategory.objects.all()
    context = {"categories": categories}
    return render(request, 'savings/category_list.html', context=context)


@login_required()
def create_account_category(request):
    form = TransactionCategoryForm()

    if request.method == 'GET':
        return render(request, "savings/categories_form.html", {'form': form})
    elif request.method == 'POST':
        form = TransactionCategoryForm(request.POST)
        if form.is_valid():
            form.save()
        else:
            print(form)
        return redirect('bank-acct-categories')


@login_required()
def update_account_category(request, pk):
    obj = get_object_or_404(TransactionCategory, id=pk)
    print(obj)
    form = TransactionCategoryForm(request.POST or None, instance=obj)
    if form.is_valid():
        form.save()
        return redirect('bank-acct-categories')
    context = {"form": form}
    return render(request, "savings/categories_form.html", context)

investment/savings/templates/savings/account_list.html
{% extends 'home/base.html' %}
{% block body_block %}

{{ account.acct_number }}
{{ account.initial_balance }}


<div class="container">
    <div class="text-right">
        <a href="{% url 'add_savings_acct'%}"><i class="bi bi-plus-square-fill text-success" style="font-size: 2rem; color: cornflowerblue;"></i></a>
    </div>
    <div class="row row-cols-1 row-cols-md-4">
        {% for account in accounts %}
            <div class="col mb-4 ">
                <div class="card shadow p-3 mb-5 bg-white rounded border-success">

                    <div class="card-body">
                        <h5 class="card-title"><a href="{% url 'get_acct_transaction' %}/{{account.id}}">{{account.acct_name}}</a> <a href="{% url 'bank-acct-details' %}/update/{{account.id}}"><i class="bi bi-pencil-square text-success" style="font-size: 1rem; color: cornflowerblue;"></i></a>
                            <a href="{%url 'add_acct_transaction' %}"><i class="bi bi-plus-square text-success" style="font-size: 1rem; color: cornflowerblue;"></i></a>
                        </h5>
                        <p class="card-text">{{account.acct_number}} ({{account.acct_type}})</p>
                        <p class="card-text">{{account.balance}} </p>
                    </div>
                </div>
            </div>
        {% endfor %}
    </div>
</div>


{% endblock %}

investment/savings/templates/savings/bankaccount_form.html
{% extends 'home/base.html' %}
{% block body_block %}
<div class="container">
<div class="text-center">
    <h3>Update Account Information</h3>
    <br>
</div>
<form method="post" action="">
{% csrf_token %}
    <div class="form-row">
        <div class="form-group col-md-3">
            <label for="id_acct_number">Account Number</label>
            <input type="text" name="acct_number" required class="form-control" id="id_acct_number"
                   value={% if form.acct_number.value %} "{{ form.acct_number.value}}" {% endif %}>
        </div>
        <div class="form-group col-md-3">
            <label for="id_acct_name">Account Name</label>
            <input type="text" name="acct_name" required class="form-control" id="id_acct_name"
                   value={% if form.acct_name.value %} "{{ form.acct_name.value}}" {% endif %}>
        </div>
        <div class="form-group col-md-3">
            <label for="id_acct_type">Account type</label>
            <select name="acct_type" required id="id_acct_type" class="form-control">
                {% if form.acct_type.value %}
                    <option selected="{{form.acct_type.value}}">{{form.acct_type.value}}</option>
                {% else %}
                    <option value selected>---------</option>
                {% endif %}
                    <option value="SAVING">SAVING</option>
                    <option value="FD">FD</option>
                    <option value="PPF">PPF</option>
            </select>
        </div>
        <div class="form-group col-md-3">
            <label for="id_initial_balance">Initial Balance</label>
            <input type="number" name="initial_balance" required step="any" class="form-control" id="id_initial_balance"
            value={% if form.initial_balance.value %} "{{form.initial_balance.value}}" {%endif%}>
        </div>
    </div>

    <div class="text-center">
        <button type="submit" class="btn btn-success" >Submit</button>
    </div>
</form>
    <br><br>
    {% if error %}
    <div class="text-center">
        <div class="alert alert-danger" role="alert">
            {{ error }}
        </div>
    </div>
    {% endif %}
</div>
{% endblock %}

investment/savings/templates/savings/banktransactions_form.html
{% extends 'home/base.html' %}
{% block body_block %}
<div class="container">
<div class="text-center">
    <h3>Update Bank Transactions</h3>
    <br>
</div>
<form method="post" action="">
{% csrf_token %}
    <div class="form-row">
        <div class="form-group col-md-2">
            <label for="id_txn_type">Transaction Type</label>
            <select name="txn_type" required id="id_txn_type" class="form-control">
                {% if form.txn_type.value %}
                    <option value="{{form.txn_type.value}}" selected>{{form.txn_type.value}}</option>
                {% else %}
                    <option value selected>--------</option>
                {% endif %}
                <option value="CREDIT">CREDIT</option>
                <option value="DEBIT">DEBIT</option>
            </select>
        </div>
        <div class="form-group col-md-3">
            <label for="id_bank_account">Bank Account</label>
            <select name="bank_account" required id="id_bank_Account" class="form-control">
                     <option value selected>--------</option>
                {% for acct in accounts %}
                    {% if acct.id == form.bank_account.value %}
                        <option value="{{acct.id}}" selected>{{acct.acct_name}}-{{acct.acct_number}}</option>
                    {% else %}
                        <option value="{{acct.id}}">{{acct.acct_name}}-{{acct.acct_number}}</option>
                    {% endif %}
                {% endfor %}
            </select>
        </div>
        <div class="form-group col-md-3">
            <label for="id_txn_category">Transaction Category</label>
            <select name="txn_category" required id="id_txn_category" class="form-control">
                <option value selected>--------</option>
                {% for cat in categories %}
                    {% if cat.id == form.txn_category.value %}
                        <option value="{{cat.id}}" selected>{{cat.category}}</option>
                    {% else %}
                        <option value="{{cat.id}}">{{cat.category}}</option>
                    {% endif %}
                {% endfor %}
            </select>
        </div>
        <div class="form-group col-md-2">
            <label for="id_txn_amount">Transaction Amount</label>
            <input type="number" name="txn_amount" required step="any" class="form-control" id="id_txn_amount"
                   value={% if form.txn_amount.value %} "{{form.txn_amount.value}}" {%endif%}>
        </div>
        <div class="form-group col-md-2">
            <label for="id_txn_date">Transaction Date</label>
            <input type="date" name="txn_date" required class="form-control" id="id_txn_date"
                   value={% if form.txn_date.value %} "{{form.txn_date.value | date:'c'}}" {%endif%}>
        </div>
    </div>
    <div class="text-center">
        <button type="submit" class="btn btn-success" >Submit</button>
    </div>
</form>
</div>
{% endblock %}

investment/savings/templates/savings/categories_form.html
{% extends 'home/base.html' %}
{% block body_block %}
<div class="container">
    <div class="text-center">
        <h3>Add Category</h3>
        <br>
    </div>
    <form method="post" action="">
    {% csrf_token %}
        <div class="form-row justify-content-md-center">
            <div class="form-group col-md-3">
                <label  for="id_category">Category</label>
                <input type="text" name="category" required id="id_category" class="form-control"
                value={% if form.category.value %} "{{form.category.value}}" {% endif %}>
            </div>
        </div>
                <div class="text-center">
                    <button type="submit" class="btn btn-success" >Submit</button>
                </div>

    </form>
    <br><br>
</div>
{% endblock %}

investment/savings/templates/savings/category_list.html
{% extends 'home/base.html' %}
{% block body_block %}

{{ account.acct_number }}
{{ account.initial_balance }}


<div class="container">
    <div class="text-center">
        <h3>Category List</h3>
        <br>
    </div>
    <div class="text-right">
        <a href="{% url 'add_savings_acct_category'%}"><i class="bi bi-plus-square-fill text-success" style="font-size: 2rem; color: cornflowerblue;"></i></a>
    </div>
    <table class="table  table-hover">
        <thead>
        <tr>
            <th scope="col">Category</th>
            <th >Edit</th>
        </tr>
        </thead>
        <tbody>
            {% for category in categories %}
            <tr>
                <td>{{category.category }}</td>
                <td><a href="categories/update/{{category.id}}"><i class="bi bi-pencil-square text-success" style="font-size: 1rem; color: cornflowerblue;"></i></a></td>
            </tr>
            {% endfor %}
        </tbody>
    </table>

</div>


{% endblock %}

investment/savings/templates/savings/transaction_list.html
{% extends 'home/base.html' %}
{% block body_block %}

{{ account.acct_number }}
{{ account.initial_balance }}


<div class="container">
    <div class="text-center">
        <h3>Transaction List</h3>
        <br>
    </div>
    <div class="text-right">
        <a href="{% url 'add_acct_transaction'%}"><i class="bi bi-plus-square-fill text-success" style="font-size: 2rem; color: cornflowerblue;"></i></a>
    </div>
    <table class="table  table-hover">
        <thead>
        <tr>
            <th scope="col">Transaction Date</th>
            <th scope="col">Transaction Type</th>
            <th scope="col">Transaction Amount</th>
            <th scope="col">Account</th>
            <th scope="col">Category</th>
            <th >Edit</th>
        </tr>
        </thead>
        <tbody>
            {% for txn in transactions %}
            <tr>
                <td>{{txn.txn_date }}</td>
                <td>{{txn.txn_type }}</td>
                <td>{{txn.txn_amount }}</td>
                <td>{{txn.bank_account.acct_name }}</td>
                <td>{{txn.txn_category.category }}</td>
                <td><a href="{% url 'get_acct_transaction' %}/update/{{txn.id}}"><i class="bi bi-pencil-square text-success" style="font-size: 1rem; color: cornflowerblue;"></i></a></td>
            </tr>
            {% endfor %}
        </tbody>
    </table>

</div>


{% endblock %}