investment/home/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views
urlpatterns = [
    path('login/', auth_views.LoginView.as_view(template_name='home/login.html'),name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='home/login.html'),name='logout'),
    path('home', views.home,name='home'),
]

investment/investment/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include
from django.contrib.auth import views as auth_views
from registrations import views
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('cal_returns.urls')),
    path('', include('chartapp.urls')),
    path('', include('home.urls')),
    path('', include('shares.urls')),
    path('', include('savings.urls')),
    path('accounts/',include("registrations.urls")),
    path("", views.login_user, name="login"),
]

investment/shares/urls.py
from . import views
from django.urls import path
urlpatterns = [
    path('shares', views.shares_home, name='shares'),
    path('share_details/<pk>/', views.shares_details, name='share_details'),
    path('add_shares', views.add_shares, name='add_shares'),
    path('update_share/<int:pk>', views.update_share, name='update_share'),
    path('get_share_list', views.get_share_list, name='get_share_list'),
    path('load_shares', views.load_shares, name='load_shares')
]

investment/shares/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.


class Shares(models.Model):
    txn_types = [
        ('BUY', 'BUY'),
        ('SELL', 'SELL'),
        ('DIV','DIV')
    ]
    symbol = models.CharField(max_length=30)
    name = models.CharField(max_length=50)
    quantity = models.FloatField()
    share_price = models.FloatField()
    txn_date = models.DateField()
    txn_type = models.CharField(max_length=4, choices=txn_types)
    user = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, blank=True)
    logo = models.CharField(max_length=150, null=True, blank=True)

class ShareList(models.Model):
    text = models.CharField(max_length=80)
    name = models.CharField(max_length=50)

investment/shares/forms.py
from django.forms import ModelForm
from .models import Shares

class SharesForm(ModelForm):
    class Meta:
        model = Shares
        exclude = ['user']

investment/shares/views.py
from django.shortcuts import render,redirect,get_object_or_404
from django.contrib.auth.decorators import login_required
from .forms import SharesForm
from .models import Shares, ShareList
from django.db.models import Avg, Count, Min, Sum
import yfinance as yf
import os
import sys
from django.http import JsonResponse
from django.templatetags.static import static
from .services.share_list import symbols
import json
#sys.path.append("../cal_returns/services")
#sys.path.append(os.path.abspath('cal_returns/services')
sys.path.append(os.path.dirname(os.path.abspath(__file__)) + "/..")
#from ..cal_returns.services.xirr import xirr
from cal_returns.services.xirr import xirr
from registrations.decorators import allowed_user

# Create your views here.

@login_required()
@allowed_user(['shares_group'])
def load_shares(request):
    f = symbols.split('\n')
    for lines in f:
        t_name, t_text = lines.split(",")
        is_exist = ShareList.objects.filter(text=f"{t_text}").exists()
        if not is_exist:
            obj = ShareList()
            obj.text = f"{t_text}"
            obj.name = f"{t_name}.NS"
            obj.save()
    return JsonResponse({'result':'Data loaded successfully'})

@login_required()
@allowed_user(['shares_group'])
def shares_details(request,pk):
    share_list = Shares.objects.filter(user=request.user).filter(symbol=pk).order_by('txn_date')
    units = {}
    investments = {}
    total_inv = 0
    total_div = 0
    for share in share_list:
        if share.symbol not in investments:
            investments[share.symbol] = []
            units[share.symbol] = 0
        multiply = 1
        #print(share)
        if share.txn_type == 'BUY':
            multiply = -1
            units[share.symbol] = units[share.symbol] + share.quantity
            total_inv = total_inv + share.quantity*share.share_price
        elif share.txn_type == 'SELL':
            units[share.symbol] = units[share.symbol] - share.quantity
        elif share.txn_type == 'DIV':
            total_div = total_div + share.share_price
        investments[share.symbol].append((share.txn_date,share.share_price*share.quantity*multiply))
    #print(investments)
    returns = {}
    for share in investments:
        symbol = yf.Ticker(share)
        hist = symbol.history(period='5d')
        returns[share] = {}
        investments[share].append((hist['Close'].index[-1].date(), hist['Close'].values[-1]*units[share]))
        returns[share]['units'] = units[share]
        #print(investments[share])
        returns[share]['returns'] = xirr(investments[share])*100
    return render(request, 'shares/share_list.html',
                  {'shares': share_list,
                   'symbol':pk,
                   'units': units[pk],
                   'total_inv':total_inv,
                   'xirr': xirr(investments[pk])*100,
                   'last_price': hist['Close'].values[-1],
                   'price_date': hist['Close'].index[-1],
                   'div':total_div,
                   'avg_price': total_inv/units[pk]
                   })


@login_required()
@allowed_user(['shares_group'])
def shares_home(request):
    share_list = Shares.objects.filter(user=request.user).values('symbol','txn_type','txn_date','share_price','logo').annotate(quantity=Sum('quantity'))
    investments = {}
    units = {}
    returns = {}
    logos = {}
    for share in share_list:
        if share['symbol'] not in investments:
            investments[share['symbol']] = []
            units[share['symbol']] = 0
        multiply = 1
        if share['txn_type'] == 'BUY':
            multiply = -1
            units[share['symbol']] = units[share['symbol']] + share['quantity']
        elif share['txn_type'] == 'SELL':
            units[share['symbol']] = units[share['symbol']] - share['quantity']
        elif share['txn_type'] == 'DIV':
            pass
        investments[share['symbol']].append((share['txn_date'],share['share_price']*share['quantity']*multiply))
        logos[share['symbol']] = share['logo']
    for share in investments:
        symbol = yf.Ticker(share)
        hist = symbol.history(period='5d')

        returns[share] = {}
        investments[share].append((hist['Close'].index[-1].date(), hist['Close'].values[-1]*units[share]))
        returns[share]['units'] = units[share]
        #print(investments[share])
        returns[share]['returns'] = xirr(investments[share])*100
        returns[share]['logo'] = logos[share]
        returns[share]['current_val'] = investments[share][-1][1]

    return render(request, 'shares/shares_home.html',{'shares': share_list, 'returns': returns})

@login_required()
@allowed_user(['shares_group'])
def add_shares(request):
    if request.method == 'POST':
        form = SharesForm(request.POST)
        if form.is_valid():
            obj = form.save(commit=False)
            obj.user = request.user
            if ShareList.objects.filter(id=obj.symbol).exists():
                symbol_obj = get_object_or_404(ShareList,id=obj.symbol)
                symbol = yf.Ticker(symbol_obj.text)
                obj.symbol = symbol_obj.text
            elif ShareList.objects.filter(text=obj.symbol).exists():
                symbol = yf.Ticker(obj.symbol)
            logo = symbol.info['logo_url']
            obj.logo = logo

            obj.save()
        else:
            pass
            #print(form)
        return redirect('shares')
    else:
        form = SharesForm()
        return render(request, 'shares/shares_form.html', {'form': form})

@login_required()
@allowed_user(['shares_group'])
def update_share(request,pk):
    #print(pk)
    obj = get_object_or_404(Shares,id=pk)
    form = SharesForm(request.POST or None, instance = obj)
    if form.is_valid():
        form_obj = form.save(commit=False)
        symbol = yf.Ticker(obj.symbol)
        logo = symbol.info['logo_url']
        #print(logo)
        form_obj.logo = logo
        form_obj.save()
        return redirect('shares')

    # add form dictionary to context
    context ={}
    context["form"] = form
    return render(request, "shares/shares_form.html", context)

@login_required()
def get_share_list(request):
    query = request.GET.get('q')
    symbol_list = ShareList.objects.filter(text__icontains=query).values()
    #print(symbol_list)
    return JsonResponse({'results':list(symbol_list)},safe=False)

investment/shares/templates/shares/share_list.html
{% extends 'home/base.html' %}
{% block body_block %}

<section> <!-- Section Start-->
    <div class="container"> <!-- Container Start-->
        <div class="columns is-multiline"> <!-- Columns start-->
            <div class="column is-2">
                    <div class="box">
                        <div class="media-content">
                            <div class="content">
                                <p>
                                    <strong>Units</strong>
                                    <br>
                                    {{ units|floatformat:0 }}
                                </p>
                            </div>
                        </div>
                    </div>
            </div>

            <div class="column is-2">
                <div class="box">
                    <div class="media-content">
                        <div class="content">
                            <p>
                                <strong>Investment</strong>
                                <br>
                                {{total_inv|floatformat:2}}
                            </p>
                        </div>
                    </div>
                </div>
            </div>

            <div class="column is-2">
                <div class="box">
                    <div class="media-content">
                        <div class="content">
                            <p>
                                <strong>Returns</strong>
                                <br>
                                {% if xirr > 0 %}
                                <i class="fa-regular fa-circle-up has-text-success"></i>
                                {% else %}
                                <i class="fa-regular fa-circle-down has-text-danger"></i>
                                {% endif %}
                                {{ xirr|floatformat:2 }}
                            </p>
                        </div>
                    </div>
                </div>
            </div>

            <div class="column is-2">
                <div class="box">
                    <div class="media-content">
                        <div class="content">
                            <p>
                                <strong>Last Price</strong>
                                <br>
                                {{last_price|floatformat:2}}
                            </p>
                        </div>
                    </div>
                </div>
            </div>

            <div class="column is-2">
                <div class="box">
                    <div class="media-content">
                        <div class="content">
                            <p>
                                <strong>Avg price</strong>
                                <br>
                                {{ avg_price|floatformat:2 }}
                            </p>
                        </div>
                    </div>
                </div>
            </div>

            
            <div class="column is-2">
                <div class="box">
                    <div class="media-content">
                        <div class="content">
                            <p>
                                <strong>Dividend</strong>
                                <br>
                                {{ div }}
                            </p>
                        </div>
                    </div>
                </div>
            </div>

        </div> <!-- Columns end-->

        <!-- Table Start-->
        <table class="table is-bordered is-striped is-narrow is-hoverable is-fullwidth">
            <thead>
                <tr>
                    <th>Date</th>
                    <th>Units</th>
                    <th>Type</th>
                    <th>Txn Price</th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
                {% for share in shares %}
                <tr>
                    <td>
                        <a  href="{% url 'update_share' share.id %}">
                            <i class="fa-solid fa-pen has-text-success is-size-7"></i>
                        </a>
                         {{ share.txn_date|date:'m/d/Y' }}
                    </td>
                    <td>{{ share.quantity|floatformat:0 }}</td>
                    <td>{{ share.txn_type }}</td>
                    <td>
                        {{ share.share_price }}
    
                    </td>
                    <td style="text-align:center">
                        <a  href="{% url 'update_share' share.id %}" style="text-align:right">
                            <i class="fa-solid fa-trash has-text-danger is-size-7"></i>
                        </a>
                    </td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
        <!-- Table End-->
    </div> <!-- Container End-->
</section> <!-- Section End-->



{% endblock %}

investment/shares/templates/shares/shares_form.html
{% extends 'home/base.html' %}
{% block body_block %}

<div class="container">

<form method="post" >

    {% csrf_token %}
    <div class="form-row">
        <div class="form-group col-md-3">
            <label for="id_symbol"><b>Symbol:</b></label>
            <!--input type="text" name="symbol" maxlength="30" required="" id="id_symbol" class="form-control"
                   value={% if form.symbol.value %} "{{form.symbol.value}}" {% endif %}-->
            <select id="id_symbol" name="symbol" class="form-control" oninput="update_name()">
                {% if form.symbol.value %}
                <option selected="{{ form.symbol.value }}">{{form.symbol.value}}</option>
                {% else %}
                <option value="" selected="">---------</option>
                {% endif %}
            </select>
        </div>

        <div class="form-group col-md-6">
            <label for="id_name"><b>Name:</b></label>
            <input type="text" name="name" maxlength="30" required="" id="id_name" class="form-control"
                   value={% if form.name.value %} "{{form.name.value}}" {% endif %}>
        </div>
        <div class="form-group col-md-3">
            <label for="id_quantity"><b>Quantity:</b></label>
            <input type="number" name="quantity" required="" id="id_quantity" class="form-control" min="1" value="{{form.quantity.value}}">
        </div>
    </div>
    <div class="form-row">
        <div class="form-group col-md-4">
            <label for="id_share_price"><b>Share Price:</b></label>
            <input type="number" name="share_price" step="any" required="" id="id_share_price" class="form-control" min="1" step="0.01" value="{{form.share_price.value}}">

        </div>
        <div class="form-group col-md-4">
            <label for="id_txn_date"><b>Date:</b></label>

            <input type="date" name="txn_date" required="" id="id_txn_date" class="form-control" value="{{form.txn_date.value|date:'Y-m-d'}}">
        </div>
        <div class="form-group col-md-4">
            <label for="id_txn_type"><b>Type:</b></label>
            <select name="txn_type" required="" id="id_txn_type" class="form-control" value="{{form.txn_type.value}}">
                {% if form.txn_type.value %}
                <option value="{{ form.txn_type.value }}">{{form.txn_type.value}}</option>
                {% else %}
                <option value="" selected="">---------</option>
                {% endif %}
                <option value="BUY">BUY</option>
                <option value="SELL">SELL</option>
                <option value="DIV">DIV</option>
            </select>
        </div>
    </div>
    <div class="text-center">
        <button type="submit" class="btn btn-success" >Submit</button>
    </div>
</form>
</div>
{% endblock %}

{% block script_block %}
<script>
var data = [
    {
        id: 0,
        text: 'SBIN.NS'
    },
    {
        id: 1,
        text: 'TCS.NS'
    },
    {
        id: 2,
        text: 'INFY.NS'
    },
    {
        id: 3,
        text: 'MARUTI.NS'
    },
    {
        id: 4,
        text: 'TATAMOTORS.NS'
    }
];
$(document).ready(function() {
$('#id_symbol').select2({
//data:data
ajax: {
    url: "{% url 'get_share_list' %}",
    dataType: 'json',
    delay: 250,
    data: function (params) {
      return {
        q: params.term, // search term
        page: params.page
      };
    },
    processResults: function (data, params) {
    console.log(data);
    return {
        results: data.results,
        pagination: {
          more: (params.page * 30) < data.total_count
        }
      };
    },
    cache: true,
    minimumInputLength: 2,

    // Additional AJAX parameters go here; see the end of this chapter for the full code of this example
  },
  minimumInputLength: 2,
});
});

function update_name()
{
    var s_list = {
        "SBIN.NS": "State Bank of India",
        "TCS.NS": "TCS",
        "INFY.NS": "Infosys"
    }
    symbol = document.getElementById("id_symbol").value;
    document.getElementById("id_name").value = symbol;

}

</script>
{% endblock %}

investment/shares/templates/shares/shares_home.html
{% extends 'home/base.html' %}
{% block body_block %}

<section>

        <div class="container">
            <div class="block has-text-right">
                <a href="" class=""><i class="fa-solid fa-cart-shopping"></i></a>
            </div>
            <div class="columns is-multiline block">
                {% for symbol,value in returns.items %}
                <div class="column is-3 ">

                    <div class="box">
                        <article class="media">
                          <div class="media-left">
                            <figure class="image is-64x64">
                              <img src="{{ value.logo }}" alt="Image">
                            </figure>
                          </div>
                          <div class="media-content">
                            <div class="content">
                              <p>
                                <strong>{{ symbol }}</strong>
                                <br>
                                
                                <nav class="level is-mobile">
                                    <div class="level-left">
                                        <div class="level-item has-text-centered">
                                            <div>
                                                <p class="heading is-size-7">Units</p>
                                                <p class="title is-size-6">{{ value.units|floatformat:0}} </p>
                                            </div>
                                        </div>
                                        <div class="level-item has-text-centered">
                                            <div>
                                                <p class="heading is-size-7">Current Value</p>
                                                <p class="title is-size-6">{{ value.current_val |floatformat:2}}</p>
                                            </div>
                                        </div>
                                        <div class="level-item has-text-centered">
                                            <div>
                                                <p class="heading is-size-7">Gain</p>
                                                {% if value.returns < 0 %}
                                                    <p class="title is-size-6 has-text-danger">{{ value.returns|floatformat:2}}</p>
                                                {% else %}
                                                    <p class="title is-size-6 has-text-success">{{ value.returns|floatformat:2}}</p>
                                                {% endif %}

                                            </div>
                                        </div>
                                    </div>
                                </nav>


                              </p>
                            </div>
                            <nav class="level is-mobile">
                              <div class="level-left">
                                <a class="level-item" aria-label="reply" href="{% url 'share_details'  symbol %}">
                                  <span class="icon is-small">
                                    <i class="fas fa-list-ul" aria-hidden="true"></i>
                                  </span>
                                </a>
                                <a class="level-item" aria-label="retweet">
                                  <span class="icon is-small">
                                    <i class="fas fa-plus" aria-hidden="true"></i>
                                  </span>
                                </a>
                                <a class="level-item" aria-label="like">
                                  <span class="icon is-small">
                                    <i class="fas fa-trash has-text-danger" aria-hidden="true"></i>
                                  </span>
                                </a>
                              </div>
                            </nav>
                          </div>
                        </article>
                      </div>

                </div>
                {% endfor %}

            </div>

        </div>
</section>

{% endblock %}