investment/cal_returns/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('stock_details', views.stock_details, name='stock_details'),
    path('inv_return_test', views.inv_return_test, name='inv_return_test'),
    path('sect_return', views.sect_return, name='sect_return'),
    #path('home', views.home, name='home'),
    path('get_inv_json', views.get_json_inv_test, name='get_json_inv_test'),
]

investment/home/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views
urlpatterns = [
    path('login/', auth_views.LoginView.as_view(template_name='home/login.html'),name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='home/login.html'),name='logout'),
    path('home', views.home,name='home'),
]

investment/investment/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include
from django.contrib.auth import views as auth_views
from registrations import views
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('cal_returns.urls')),
    path('', include('chartapp.urls')),
    path('', include('home.urls')),
    path('', include('shares.urls')),
    path('', include('savings.urls')),
    path('accounts/',include("registrations.urls")),
    path("", views.login_user, name="login"),
]

investment/cal_returns/forms.py
from django import forms


class StockForm(forms.Form):
    symbol_name = forms.CharField(label='Symbol', 
                                  max_length=20,
                                  widget=forms.TextInput(attrs={'class':'form-control'}))
    start_date = forms.DateField(widget=forms.TextInput(attrs={'class':'form-control'}))
    end_date = forms.DateField(widget=forms.TextInput(attrs={'class':'datepicker'}))


class InvStockForm(forms.Form):
    risk_options = ((10, 'Low'),
                    (20, 'Medium'),
                    (50, 'High'))
    symbol_name = forms.CharField(label='Symbol',
                                  max_length=20,
                                  widget=forms.TextInput(attrs={'class':'form-control'}))
    start_date = forms.DateField(widget=forms.TextInput(attrs={'class':'form-control'}))
    end_date = forms.DateField(widget=forms.TextInput(attrs={'class':'form-control'}))
    risk_ape = forms.CharField(label="Risk Appetite", widget=forms.Select(choices=risk_options))



class SectReturnForm(forms.Form):
    sector_choices = ([('Bank', 'Bank'),
                       ('IT','IT'),
                       ('ETF','ETF'),
                       ('Auto','Auto'),
                       ('NIFTY50','NIFTY50')])
    sector = forms.ChoiceField(widget=forms.Select(attrs={'class': 'form-control'}),
                               choices=sector_choices)
    start_date = forms.DateField(widget=forms.TextInput(attrs={'class':'datepicker'}))
    end_date = forms.DateField(widget=forms.TextInput(attrs={'class':'datepicker'}))

investment/cal_returns/views.py
from django.shortcuts import render, get_object_or_404, HttpResponse
import sys
from datetime import date, datetime
from .forms import StockForm, InvStockForm, SectReturnForm
from .services.query_stocks import  new_inv_test,get_results
from django.http import JsonResponse
import os
from django.contrib.auth.decorators import login_required
sys.path.append(os.path.abspath('.'))
from shares.models import ShareList
from django.contrib.auth.decorators import login_required
from registrations.decorators import allowed_user
from render_block import render_block_to_string
import json


@login_required()
def stock_details(request):
    if request.method == 'POST':
        form = StockForm(request.POST)
        if form.is_valid():
            symbol = form.cleaned_data['symbol_name']
#            series = form.cleaned_data['series']
            start_date = form.cleaned_data['start_date']
            end_date = form.cleaned_data['end_date']

            data, min_val, max_val = get_results(symbol, 'EQ', start_date, end_date)
            return render(request, 'cal_returns/stock_details.html', {'form': form,
                                                                      'data': data,
                                                                      'min': min_val,
                                                                      'max': max_val})
    else:
        form = StockForm()
        return render(request, 'cal_returns/stock_details.html', {'form': form})

@login_required()
@allowed_user(['test_group'])
def inv_return_test(request):
    if request.method == 'POST':
        form = InvStockForm(request.POST)
        if form.is_valid():

            symbol = form.cleaned_data['symbol_name']
            symbol_temp = ""
            if ShareList.objects.filter(id=symbol).exists():
                symbol_obj = get_object_or_404(ShareList,id=symbol)
                symbol_temp = symbol_obj.text
            elif ShareList.objects.filter(text=symbol).exists():
                symbol_temp =  symbol

            symbol = symbol_temp
            start_date = form.cleaned_data['start_date']
            end_date = form.cleaned_data['end_date']
            no_of_shares = 1 
            multiply = 1.4 
            moving_average = 10 
            moving_average = int(form.cleaned_data['risk_ape'])

            data, xirr_value, inv_to_proceed, tot_inv, tot_ret = new_inv_test(symbol, 'EQ', start_date, end_date,
                                                                          no_of_shares, multiply, moving_average)
            abs_ret = (tot_ret - tot_inv)/tot_inv * 100
            date_list = [datetime(year=x[0].year, month=x[0].month, day=x[0].day).timestamp()*1000+86400000 for x in data]
            price_list = [round(x[1],2) for x in data]
            price_list[-1] = price_list[-2]
            price1_list = [round(x[2],2) for x in data]
            msg = f"{price_list[-1]} invested would have given {price1_list[-1]}"
            html = render_block_to_string('cal_returns/inv_return_test_par.html', 'inv-test-result',{'form': form,
                                                                                     'data': data,
                                                                                     'symbol': symbol,
                                                                                     'xirr': xirr_value,
                                                                                     'inv_to_proceed': inv_to_proceed,
                                                                                     'total_inv': tot_inv,
                                                                                     'total_ret': tot_ret,
                                                                                     'abs_return': abs_ret,
                                                                                     'date_list': date_list,
                                                                                     'price_list': price_list,
                                                                                     'price1_list': price1_list,
                                                                                     'msg':msg})
            return HttpResponse(html)

    else:
        form = InvStockForm()
        return render(request, 'cal_returns/inv_return_test_par.html', {'form': form})


@login_required()
@allowed_user(['shares_group'])
def sect_return(request):
    if request.method == 'POST':
        form = SectReturnForm(request.POST)
        if form.is_valid():
            sector = form.cleaned_data['sector']
            start_date = form.cleaned_data['start_date']
            end_date = form.cleaned_data['end_date']
            no_of_shares = 10 
            multiply = 1.4 
            moving_average = 10 
            symbols = []
            if sector == 'IT':
                symbols = ['WIPRO.NS', 'TCS.NS', 'INFY.NS', 'TECHM.NS', 'NIITLTD.NS', 'HCLTECH.NS', 'TATAELXSI.NS', 'MINDTREE.NS', ]
            if sector == 'Auto':
                symbols = ['ASHOKLEY.NS', 'HEROMOTOCO.NS', 'M&M.NS', 'APOLLOTYRE.NS', 'MRF.NS', 'BAJAJ-AUTO.NS', 'MARUTI.NS', 'EICHERMOT.NS',
                           'TVSMOTOR.NS', 'TATAMOTORS.NS', 'BOSCHLTD.NS', 'EXIDEIND.NS', 'AMARAJABAT.NS', 'BHARATFORG.NS']
            if sector == 'Bank':
                symbols = ['IDFCFIRSTB.NS', 'INDUSINDBK.NS', 'YESBANK.NS', 'SBIN.NS', 'AXISBANK.NS', 'PNB.NS', 'HDFCBANK.NS', 'BANKBARODA.NS',
                           'RBLBANK.NS', 'ICICIBANK.NS', 'KOTAKBANK.NS', 'FEDERALBNK.NS']
            if sector == 'ETF':
                symbols = ['NIFTYBEES.NS', 'KOTAKBKETF.NS', 'CPSEETF.NS', 'SETFNIFBK.NS', 'SETFNIF50.NS', 'BANKBEES.NS', 'ICICINIFTY.NS',
                           'GOLDBEES.NS', 'ICICILIQ.NS']
            if sector == 'NIFTY50':
                symbols = [
                    'ADANIPORTS.NS',
                    'ASIANPAINT.NS',
                    'AXISBANK.NS',
                    'BAJAJ-AUTO.NS',
                    'BAJFINANCE.NS',
                    'BAJAJFINSV.NS',
                    'BPCL.NS',
                    'BHARTIARTL.NS',
                    'BRITANNIA.NS',
                    'CIPLA.NS',
                    'COALINDIA.NS',
                    'DIVISLAB.NS',
                    'DRREDDY.NS',
                    'EICHERMOT.NS',
                    'GRASIM.NS',
                    'HCLTECH.NS',
                    'HDFCBANK.NS',
                    'HDFCLIFE.NS',
                    'HEROMOTOCO.NS',
                    'HINDALCO.NS',
                    'HINDUNILVR.NS',
                    'HDFC.NS',
                    'ICICIBANK.NS',
                    'ITC.NS',
                    'IOC.NS',
                    'INDUSINDBK.NS',
                    'INFY.NS',
                    'JSWSTEEL.NS',
                    'KOTAKBANK.NS',
                    'LT.NS',
                    'M&M.NS',
                    'MARUTI.NS',
                    'NTPC.NS',
                    'NESTLEIND.NS',
                    'ONGC.NS',
                    'POWERGRID.NS',
                    'RELIANCE.NS',
                    'SBILIFE.NS',
                    'SHREECEM.NS',
                    'SBIN.NS',
                    'SUNPHARMA.NS',
                    'TCS.NS',
                    'TATACONSUM.NS',
                    'TATAMOTORS.NS',
                    'TATASTEEL.NS',
                    'TECHM.NS',
                    'TITAN.NS',
                    'UPL.NS',
                    'ULTRACEMCO.NS',
                    'WIPRO.NS'
                ]
            if len(symbols) == 0:
                symbols = ['NIFTYBEES']
            sect_ret_results = []
            for symbol in symbols:
                data, xirr_value, inv_to_proceed, tot_inv, tot_ret = new_inv_test(symbol, 'EQ', start_date, end_date,
                                                                              no_of_shares, multiply, moving_average)
                sect_ret_results.append((symbol, xirr_value, inv_to_proceed, data[-1][0], data[-1][1]))
            html =  render_block_to_string('cal_returns/sect_return.html', 'sec_return_result', {'form': form,
                                                                    'data': sect_ret_results,
                                                                    })
            return HttpResponse(html)
    else:
        form = SectReturnForm()
        return render(request, 'cal_returns/sect_return.html', {'form': form})

@login_required()
@allowed_user(['shares_group'])
def get_json_inv_test(request):
    post_msg = json.loads(request.body.decode("utf-8"))
    symbol = post_msg.get("symbol")
    start_date = post_msg.get("start_date")
    end_date = post_msg.get("end_date")
    category = post_msg.get("category")
    if symbol:
        symbol = symbol
    else:
        symbol = 'NIFTYBEES.NS'
    symbolobj = ShareList.objects.filter(text=symbol)
    symbol = symbolobj[0].name

    data, xirr_value, inv_to_proceed, tot_inv, tot_ret = new_inv_test(symbol, 'EQ', start_date, end_date,
                                                                      10, 1.4, int(category))
    abs_ret = (tot_ret - tot_inv)/tot_inv * 100
    date_list = [datetime(year=x[0].year, month=x[0].month, day=x[0].day).timestamp()*1000+86400000 for x in data]
    price_list = [round(x[1],2) for x in data]
    price_list[-1] = price_list[-2]
    price1_list = [round(x[2],2) for x in data]
    msg = f"{price_list[-1]} invested would have given {price1_list[-1]}"
    response = JsonResponse({'symbol':  symbol,
                             'xirr': xirr_value,
                             'inv_value': round(inv_to_proceed,2),
                             'inv_to_proceed': round(inv_to_proceed,2),
                            'total_inv': round(tot_inv,2),
                            'total_ret': round(tot_ret,2),

investment/home/views.py
from django.shortcuts import render
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import Group

# Create your views here.
@login_required
def home(request):
    return render(request,'home/home.html', {})

investment/cal_returns/templates/cal_returns/home.html
{% extends "cal_returns/base.html" %}
{% block title %}Investment and Portfolio{% endblock %}
{% block body %}

{% endblock %}

investment/cal_returns/templates/cal_returns/inv_return_test.html
{% extends "home/base.html" %}
{% load static %}
{% block title %}
Investment Test

{% endblock %}
{% block body_block %}
<div class="container is-fluid" >
    <form action="inv_return_test" 
          method="post" 
          hx-post="{% url 'inv_return_test' %}" 
          hx-target="#inv-test-result"
          hx-indicator="#indicator"
          hx-swap="outerHTML swap:1s">
        {% csrf_token %}
        <div class="columns is-mobile">


                    <div class="column is-5-desktop is-4-mobile is-size-7">
                        <div class="field is-horizontal">
                            <div class="field-label is-normal">
                              <label class="label">Start Date</label>
                            </div>
                            <div class="field-body">
                              <div class="field">
                                <p class="control">
                                    <input type="date"  class="input is-size-7" name="start_date" class="form-control" required="" id="id_start_date">
                                </p>
                              </div>
                            </div>
                          </div>
                    </div>
                    <div class="column is-5-desktop is-4-mobile is-size-7">
                        <div class="field is-horizontal">
                            <div class="field-label is-normal">
                              <label class="label">End Date</label>
                            </div>
                            <div class="field-body">
                              <div class="field">
                                <p class="control">
                                    <input type="date"  class="input is-size-7" name="end_date" class="form-control" required="" id="id_end_date">
                                </p>
                              </div>
                            </div>
                        </div>
                    </div>
                    <div class="column is-2-desktop is-4-mobile is-size-7">
                      <div class="field is-horizontal">
                          <div class="field-label is-normal">
                            <label class="label ">Symbol</label>
                          </div>
                          <div class="field-body">
                            <div class="field">
                              <p class="control is-size-7">
                                  <select id="id_symbol_name" name="symbol_name" required class="select is-size-7">
                                      <option value="" selected="">---------------</option>
                                  </select>
                              </p>
                            </div>
                          </div>
                        </div>
                    </div>
                    <!--div class="form-group col-4 col-md-4 col-sm-4">
                        <label for="id_symbol_name">Symbol</label>
                        <select id="id_symbol_name" name="symbol_name" class="form-control" required >
                            <option value="" selected="">---------------</option>
                        </select>
                    </div>
                    <div class="form-group col-4 col-md-4 col-sm-6">
                        <label for="id_no_of_shares">Shares</label>
                        {{ form.no_of_shares }}
                    </div>
                    <div class="form-group col-4 col-md-4 col-sm-6">
                        <label for="multiply">Multiply</label>
                        {{ form.multiply }}
                    </div>
                    <div class="form-group col-4 col-md-4 col-sm-6">
                        <label for="moving_average">MA</label>
                        {{ form.moving_average }}
                    </div>
                    <div class="form-group col-4 col-md-4 col-sm-4">
                        <label for="start_date">Start Date</label>
                        <input type="date" name="start_date" class="form-control" required="" id="id_start_date">
                    </div>
                    <div class="form-group col-4 col-md-4 col-sm-4">
                        <label for="end_date">End Date</label>
                        <input type="date" name="end_date" class="form-control" required="" id="id_end_date">
                    </div-->



        </div>
        <div class="has-text-centered">
          <button type="submit" class="button is-small">
              Submit&nbsp<img id="indicator" class="htmx-indicator" src="{% static 'home/svg-loaders/circles.svg' %}"/>
          </button>
      </div>
    </form>
    <br>
</div>
    <!--div class="row justify-content-center">
        <div class="loader" align="center"></div>
    </div-->
    
    
        {% block inv-test-result %}

        <div id="inv-test-result" class="inv-result">
          <div style="display: none" id="priceData" data-json="{{ price_list|safe }}"></div>
          <div style="display: none" id="price1Data" data-json="{{ price1_list|safe }}"></div>
          <div style="display: none" id="dateData" data-json="{{ date_list }}"></div>
        {% if xirr %}
     
        <nav class="level is-mobile is-hidden-desktop">
            <div class="level-item has-text-centered">
              <div>
                <p class="heading is-size-7-mobile">Symbol</p>
                <p class="title is-size-7-mobile">symbol</p>
              </div>
            </div>
            <div class="level-item has-text-centered">
              <div>
                <p class="heading is-size-7-mobile">Returns (XIRR)</p>
                <p class="title is-size-7-mobile 
                          {% if '-' in xirr %} 
                          has-text-danger 
                          {% else %} 
                          has-text-success
                          {% endif %}">
                {{ xirr }}
                </p>
              </div>
            </div>
            <div class="level-item has-text-centered">
              <div>
                <p class="heading is-size-7-mobile">Investment Price</p>
                <p class="title is-size-7-mobile">{{ inv_to_proceed|floatformat:2 }}</p>
              </div>
            </div>
        </nav>
 
        <nav class="level is-hidden-touch">
            <div class="level-item has-text-centered">
              <div>
                <p class="heading is-size-7-mobile">Investment Price</p>
                <p class="title is-size-7-mobile">{{ inv_to_proceed|floatformat:2 }}</p>
              </div>
            </div>
            <div class="level-item has-text-centered">
              <div>
                <p class="heading is-size-7-mobile">Returns (XIRR)</p>
                <p class="title is-size-7-mobile 
                          {% if '-' in xirr %} 
                          has-text-danger 
                          {% else %} 
                          has-text-success
                          {% endif %}">
                {{ xirr }}
                </p>
              </div>
            </div>
            <div class="level-item has-text-centered">
              <div>
                <p class="heading is-size-7-mobile">Total Investment</p>
                <p class="title is-size-7-mobile">{{ total_inv|floatformat:2 }}</p>
              </div>
            </div>
            <div class="level-item has-text-centered">
                <div>
                    <p class="heading">Symbol</p>
                    <p class="title is-size-7-mobile">INFY.NS</p>
                </div>
                </div>
            <div class="level-item has-text-centered">
              <div>
                <p class="heading">Total Returns</p>
                <p class="title is-size-7-mobile
                          {% if total_inv < total_ret %} 
                          has-text-success 
                          {% else %} 
                          has-text-danger 
                          {% endif %}">
                          {{ total_ret|floatformat:2 }}
                </p>
              </div>
            </div>
            <div class="level-item has-text-centered">
                <div >
                  <p class="heading is-size-7-mobile">Absolute Returns</p>
                  <p class="title is-size-7-mobile 
                            {% if abs_return > 0 %} 
                            has-text-success 
                            {% else %} 
                            has-text-danger 
                            {% endif %}">
                            {{ abs_return|floatformat:2 }}%
                    </p>
                </div>
              </div>
        </nav>


            <!--div class="row justify-content-center">
                <div class="card text-white bg-success mb-3 " style="max-width: 18rem;">
                    <div class="card-header" id="id-card-header" >Investment Details and Returns</div>
                    <div class="card-body">
                        <div class="alert alert-primary" role="alert">
                            Investment Price - {{ inv_to_proceed|floatformat:2 }}
                        </div>
                        <div class="alert alert-primary" role="alert">
                            Returns (XIRR) - {{ xirr }}
                        </div>
                        <div class="alert alert-primary" role="alert">
                            Total Investment  - {{ total_inv|floatformat:2 }}
                        </div>
                        <div class="alert alert-primary" role="alert">
                            Total Returns  - {{ total_ret|floatformat:2 }}
                        </div>
                        <div class="alert alert-primary" role="alert">
                            Abs Returns  - {{ abs_return|floatformat:2 }}
                        </div>
                    </div>
                </div>
            </div-->

        {% endif %}
        <br>
        {% if msg %}
        {{msg}}
        {% endif %}
        <br>
          <div class="columns">
            <div class="column">
              <div id="chart"></div>
            </div>
            <div class="column">
              {% if data %}
              <div class="table-responsive-sm">
                  <table class="table table-striped table-bordered table-sm" style="width:100%" id="example">
                      <thead>
                          <tr>
                              <th>Date</th>
                              <!--th>Close Price</th>
                              <th>Moving Average</th-->
                              <th>Price</th>
                              <!--th>Investment</th-->
                          </tr>
                      </thead>
                      <tbody>
                          {% for date,price,ma,shares,investment in data %}
                          <tr>
                              <td>{{ date|date:'Y-m-d' }}</td>
                              <!--td>{{ price|floatformat:2 }}</td>
                              <td>{{ ma|floatformat:2 }}</td-->
                              <td>{{ shares|floatformat:2 }}</td>
                              <!--td>{{ investment|floatformat:2 }}</td-->
                          </tr>
                          {% endfor %}
                      </tbody>
                  </table>
              </div>
              {% endif %}
            </div>
          </div>
        </div>
        {% endblock %}
    
    
</div>


{% endblock %}

{% block script_block %}
<script>

function loadJson(selector) {
  return JSON.parse(document.querySelector(selector).getAttribute('data-json'));
}
var data = [
    {
        id: 0,
        text: 'SBIN.NS'
    },
    {
        id: 1,
        text: 'TCS.NS'
    },
    {
        id: 2,
        text: 'INFY.NS'
    },
    {
        id: 3,
        text: 'MARUTI.NS'
    },
    {
        id: 4,
        text: 'TATAMOTORS.NS'
    }
];
$(document).ready(function() {
$('#id_symbol_name').select2({
//data:data
ajax: {
    url: "{% url 'get_share_list' %}",
    dataType: 'json',
    delay: 250,
    data: function (params) {
      return {
        q: params.term, // search term
        page: params.page
      };
    },
    processResults: function (data, params) {
    console.log(data);
    return {
        results: data.results,
        pagination: {
          more: (params.page * 30) < data.total_count
        }
      };
    },
    cache: true,
    minimumInputLength: 2,

    // Additional AJAX parameters go here; see the end of this chapter for the full code of this example
  },
  minimumInputLength: 2,
});
});


function draw_chart(){
// For graph
console.log(typeof(loadJson('#priceData')))
  var options = {
    chart: {
      type: 'line'
    },
    series: [{
      name: 'sales',
      //data: [30,40,35,50,49,60,70,91,125]
      data: loadJson('#priceData')
    },
    {
      name: 'sales1',
      //data: [30,40,35,50,49,60,70,91,125]
      data: loadJson('#price1Data')
    }],
    xaxis: {
      //categories: [1991,1992,1993,1994,1995,1996,1997, 1998,1999]
      categories: loadJson('#dateData'),
      type: 'date'
    },
    stroke:{
      width:1.5
    }
  }

  var chart = new ApexCharts(document.querySelector("#chart"), options);

  chart.render()
}
//draw_chart()
document.body.addEventListener('htmx:afterSettle', function(evt) {
  console.log("I am calling the function")
  draw_chart(); // add a new parameter into the mix
  $('#example').DataTable( {
        dom: 'Blfrtip',
        buttons: [
            'copy', 'csv', 'excel', 'pdf', 'print'
        ]
    } );
});


</script>
{% endblock %}

investment/cal_returns/templates/cal_returns/sect_return.html
{% extends "home/base.html" %}
{% load static %}
{% block title %}Investment Test{% endblock %}
{% block body_block %}

<div class="container">
<form action="sect_return" 
      method="post" 
      hx-post="{% url 'sect_return' %}"           
      hx-target="#sect-result"
      hx-indicator="#indicator"
      hx-swap="outerHTML">
    {% csrf_token %}
    <div class="form-row">
        <div class="form-group col-md-4 col-sm-4">
            <label for="id_sector">Sector</label>
            {{ form.sector }}

        </div>
        <!--div class="form-group col-md-4 col-sm-6">
            <label for="id_no_of_shares">no_of_shares</label>
            {{ form.no_of_shares }}
        </div>
        <div class="form-group col-md-4 col-sm-6">
            <label for="multiply">Multiply</label>
            {{ form.multiply }}
        </div>
        <div class="form-group col-md-4 col-sm-6">
            <label for="moving_average">Moving Average</label>
            {{ form.moving_average }}
        </div-->
        <div class="form-group col-md-4 col-sm-4">
            <label for="start_date">Start Date</label>
            <input type="date" name="start_date" class="form-control" required="" id="id_start_date">
        </div>
        <div class="form-group col-md-4 col-sm-4">
            <label for="end_date">End Date</label>
            <input type="date" name="end_date" class="form-control" required="" id="id_end_date">
        </div>

        <div class="d-grid gap-4 col-1 mx-auto">
            <button type="submit" class="btn btn-success" id="sect_return">Submit</button>
        </div>
    </div>
    <br>


</form>

<div id="resp-error"></div>

<br>
<div class="row justify-content-center">
    <img id="indicator" class="htmx-indicator" src="{% static 'home/svg-loaders/circles.svg' %}"/>
</div>
<br>
<br>
    {% block sec_return_result %}
    <div id="sect-result">
        {% if data %}
        <table class="table table-striped table-bordered" style="width:100%" id="example">
            <thead>
                <tr>
                    <th>Symbol</th>
                    <th>Return</th>
                    <th>Next Investment Price</th>
                    <th>Last Traded Date</th>
                    <th>Last Traded Price</th>
                </tr>
            </thead>
            <tbody>
                {% for symbol,returns,price,dt,pr in data %}
                <tr>
                    <td>{{ symbol }}</td>
                    <td>{{ returns }}</td>
                    <td>{{ price|floatformat:2 }}</td>
                    <td>{{ dt }}</td>
                    <td>{{ pr|floatformat:2 }}</td>
                </tr>
                {% endfor %}
            </tbody>
        </table>

        {% endif %}
    </div>
    {% endblock %}

    </div>

</div>
{% endblock %}

{% block script_block %}
<script>
    
    document.body.addEventListener('htmx:responseError', function(evt) {
    console.log("I got the error");
    error_div = document.getElementById("resp-error");
    error_div.classList.add("alert");
    error_div.classList.add("alert-danger");
    error_div.innerHTML = "Error in getting the response";
    });

    document.body.addEventListener('htmx:beforeRequest', function(evt) {
    error_div = document.getElementById("resp-error");
    error_div.classList.remove("alert");
    error_div.classList.remove("alert-danger");
    error_div.innerHTML = "";
    });
</script>
{% endblock %}

investment/cal_returns/templates/cal_returns/xirr.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap-theme.min.css">
    <title>This is first page</title>
</head>
<body>
{{ xirr }}
</body>
</html>